theme: minima
title: Ducks on Moon
author: Mehrshad Baqerzadegan
email: MehrshadBaqerzadegan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   An individual who tries to graduate from computer science and become a programmer.
# social links
twitter_username: sinfulspinoza # DO NOT include the @ character, or else the build will fail!
github_username:  m-b850 # DO NOT include the @ character, or else the build will fail!
linkedin_username: mehrshad-baqerzadegan
show_excerpts: true # set to false to remove excerpts on the homepage
show_description: false
