theme: minima

title: Ducks on Moon
description: >- # this means to ignore newlines until "baseurl:"
   An individual who tries to graduate from computer science and become a programmer.

author:
  name: Mehrshad Baqerzadegan
  email: MehrshadBaqerzadegan@gmail.com

social_links:
 twitter: sinfulspinoza
 github: m-b850
 linkedin: mehrshad-baqerzadegan

show_excerpts: false
