theme: minima
title: Ducks on Moon
author: Mehrshad Baqerzadegan
email: MehrshadBaqerzadegan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
twitter_username: sinfulspinoza # DO NOT include the @ character, or else the build will fail!
github_username:  m-b850 # DO NOT include the @ character, or else the build will fail!
linkedin_username: mehrshad-baqerzadegan
show_excerpts: true # set to false to remove excerpts on the homepage
