theme: minima

title: Ducks on Moon
description: >- # this means to ignore newlines until "baseurl:"
   An individual who tries to graduate from computer science and become a programmer.

author:
   name: Mehrshad Baqerzadegan
   email: MehrshadBaqerzadegan@gmail.com

social_links:
   linkedin_username: mehrshad-baqerzadegan
   twitter_username: sinfulspinoza
   github_username:  m-b850


show_excerpts: false
